// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6qNiu47T_09ykIgfDEJje0tMzjKU8Jao',
    appId: '1:178088123232:web:1bb5c22414a7465b3cdc05',
    messagingSenderId: '178088123232',
    projectId: 'local-deal-app-fresh',
    authDomain: 'local-deal-app-fresh.firebaseapp.com',
    storageBucket: 'local-deal-app-fresh.firebasestorage.app',
    measurementId: 'G-3Z13NVGFDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXQZF7F_MbE64Q9yFS1fp4r9CMeKX9DiY',
    appId: '1:178088123232:android:16715d501a8adbe23cdc05',
    messagingSenderId: '178088123232',
    projectId: 'local-deal-app-fresh',
    storageBucket: 'local-deal-app-fresh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiArgX89TVgqWTA7musUgRneuPTbmG94c',
    appId: '1:178088123232:ios:251a760ed8cdf1543cdc05',
    messagingSenderId: '178088123232',
    projectId: 'local-deal-app-fresh',
    storageBucket: 'local-deal-app-fresh.firebasestorage.app',
    androidClientId: '178088123232-flfuc1ho6lqi00o8ombs8oamh1rmelp3.apps.googleusercontent.com',
    iosClientId: '178088123232-9u12mofame9l1j0cjtm9phtbp4rt2obe.apps.googleusercontent.com',
    iosBundleId: 'com.example.localDealApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiArgX89TVgqWTA7musUgRneuPTbmG94c',
    appId: '1:178088123232:ios:251a760ed8cdf1543cdc05',
    messagingSenderId: '178088123232',
    projectId: 'local-deal-app-fresh',
    storageBucket: 'local-deal-app-fresh.firebasestorage.app',
    androidClientId: '178088123232-flfuc1ho6lqi00o8ombs8oamh1rmelp3.apps.googleusercontent.com',
    iosClientId: '178088123232-9u12mofame9l1j0cjtm9phtbp4rt2obe.apps.googleusercontent.com',
    iosBundleId: 'com.example.localDealApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6qNiu47T_09ykIgfDEJje0tMzjKU8Jao',
    appId: '1:178088123232:web:e3f398f7105e129b3cdc05',
    messagingSenderId: '178088123232',
    projectId: 'local-deal-app-fresh',
    authDomain: 'local-deal-app-fresh.firebaseapp.com',
    storageBucket: 'local-deal-app-fresh.firebasestorage.app',
    measurementId: 'G-JY21XF5PEM',
  );

}